api:
  security:
    auth0:
      audience: heroku-api-oauth
      issuer-uri: https://dry-sea-3477.eu.auth0.com/
      allowed-origins:
        - "https://heroku-react-oauth.herokuapp.com"
        - "http://localhost:3000"

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          cors: DEBUG


